CREATE DATABASE IF NOT EXISTS bai4;
USE bai4;

CREATE TABLE USERS (
    UserID INT PRIMARY KEY,
    FullName VARCHAR(100),
    Phone INT
);

-- Sửa lỗi
ALTER TABLE USERS ADD Phone_new VARCHAR(15);
UPDATE USERS SET Phone_new = Phone;
ALTER TABLE USERS DROP COLUMN Phone;
ALTER TABLE USERS CHANGE Phone_new Phone VARCHAR(15);